name: Docker build push and commit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.short-sha.outputs.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - uses: benjlevesque/short-sha@v2.0
        id: short-sha
        with:
          length: 6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: pawelkostylahuuuge/argocd_demo_app:${{ outputs.short-sha }}
          build-args: |
            GIT_REVISION=${{ outputs.short-sha }}
#   deploy-pull-request:  
#     runs-on: ubuntu-latest
    
#     steps:

  update-configrepo:  
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    
    steps:
      - uses: actions/checkout@master
        with:
          repository: pawelkostyla/argocd-configrepo
          ref: master
          path: configrepo
          token: ${{ secrets.ARGOCD_CONFIGREPO_TOKEN }}
        if: github.event_name != 'pull_request'
      - name: Update application.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'projects/applications/staging/demo-app/values.yaml'
          propertyPath: 'image.tag'
#           value: ${{ steps.short-sha.outputs.sha }}
          commitChange: true
          updateFile: true
          targetBranch: master
          branch: master
          workDir: configrepo
          masterBranchName: master
          message: 'Update pawelkostylahuuuge/argocd_demo_app image Version to ${{ needs.build-and-push-docker.outputs.short-sha }}'
          repository: pawelkostyla/argocd-configrepo
          token: ${{ secrets.ARGOCD_CONFIGREPO_TOKEN }}
          changes: |
            {
              "projects/applications/staging/demo-app/values.yaml": {
                "image.tag": ${{ needs.build-and-push-docker.outputs.short-sha }}
              },
              "projects/applications/production/demo-app/values.yaml": {
                "image.tag": ${{ needs.build-and-push-docker.outputs.short-sha }}
              }
            }
        if: github.event_name != 'pull_request'
